import { drizzle } from 'drizzle-orm/node-postgres';
import { pool } from './pool.js';
import * as tables from './schema/schema.js';
import * as relations from './schema/relations.js';

/**
 * Drizzle bound to the shared `pg` pool, used as a typed query builder *over*
 * the frozen `schema.sql` (Day-0 lock #1) — it never owns migrations. The
 * `schema`/`relations` modules are machine-generated by `npm run db:introspect`
 * (`drizzle-kit pull`) from the loaded DB; `schema.sql` stays canonical, this
 * only mirrors it into TypeScript for typed queries + the relational API.
 */
const schema = { ...tables, ...relations };

export const db = drizzle(pool, { schema });
