import { drizzle } from 'drizzle-orm/node-postgres';
import { pool } from './pool.js';

/**
 * Drizzle bound to the shared `pg` pool, used as a typed query builder *over*
 * the frozen `schema.sql` (Day-0 lock #1) — it never owns migrations.
 *
 * No schema object is passed yet: the typed table surface is generated by
 * `npm run db:introspect` (`drizzle-kit pull`) against the loaded DB and
 * committed as `src/db/schema/`. Until then, raw SQL via this client works
 * (Day 1 only needs `SELECT 1`). When the introspected schema lands, pass it
 * here as `drizzle(pool, { schema })`.
 */
export const db = drizzle(pool);
