/**
 * THE shared API↔client wire contract — single source of truth.
 *
 * This module is **dependency-free on purpose**: no imports (not Drizzle, not
 * anything). It is the file the staff portal's `src/api/contracts.ts` is
 * GENERATED from (verbatim + a banner, via the portal's `npm run sync:contracts`),
 * so it must never drag server code (Drizzle schema, Node APIs) into a browser
 * bundle. Keep it pure types + literal value tuples + pure helpers.
 *
 * Two halves:
 *   1. **Enum unions + value tuples.** Declared here as literals. Their values
 *      are canonically owned by the DB (`schema.sql` → Drizzle `pgEnum`); the
 *      literals here are a hand-maintained mirror that `contracts/conformance.ts`
 *      pins to the Drizzle enums with a compile-time `Equal<…>` assert — so if
 *      `schema.sql` changes an enum, `tsc` fails until this file is updated.
 *      (We assert rather than rewire `pgEnum(...)` because `schema.ts` is
 *      drizzle-introspection-generated and a `db:introspect` pull would clobber
 *      any hand-wired tuple import.)
 *   2. **Wire interfaces.** The JSON shapes the API emits. snake_case keys are
 *      intentional — they're the literal JSON keys on the wire. These have no
 *      other canonical home, so THIS file is their single definition; the API's
 *      `lib/*Wire.ts` + the staff routes import them from here.
 */

// ---- contract version ------------------------------------------------------

/**
 * Semver for this contract. Bump on EVERY edit to this file, log the change in
 * `src/contracts/CHANGELOG.md`, and resync BOTH generated clients (portal +
 * mobile `npm run sync:contracts`) in their own repos' commits:
 *   major — remove/rename/retype an existing field or enum member
 *   minor — additive (new field, interface, enum member, tuple value)
 *   patch — comment/doc-only (still changes generated bytes → still resync)
 */
export const WIRE_CONTRACT_VERSION = '1.9.0';

// ---- enum unions -----------------------------------------------------------

export type ServiceCategory =
  | 'day-school'
  | 'day-care'
  | 'group-class'
  | 'private-lesson'
  | 'board-and-train'
  | 'boarding'
  | 'evaluation';

export type BookingStatus = 'upcoming' | 'past' | 'cancelled';

export type RequestStatus =
  | 'submitted'
  | 'approved'
  | 'approved-awaiting-payment'
  | 'converted'
  | 'cancelled';

export type ThreadCategory = 'sessions' | 'billing' | 'enrollment' | 'other';

/** Stripe settle state for one `charges` row. Mirrors the `charge_status`
 *  pgEnum (pinned in `conformance.ts`). Entered the contract in 1.7.0 with
 *  `InvoicePayWire`, which reports it; `chargesRepository` imports it from here
 *  so the DB status and the wire status cannot drift into two definitions. */
export type ChargeStatus = 'requires_payment' | 'succeeded' | 'failed' | 'refunded';

/**
 * Why a confirm stopped short of `succeeded`, at the domain level. Three
 * different true sentences with three different next actions for the owner:
 * the card needs verification we cannot complete, the card was declined, or
 * the payment is still in flight and must NOT be retried.
 *
 * This exists because `ChargeStatus` cannot carry the distinction -- it is
 * pinned to the `charge_status` pgEnum, and the mapping into it collapses
 * Stripe's requires_payment_method / requires_confirmation / requires_action /
 * processing / requires_capture into the single value `requires_payment`. The
 * copy the owner reads depends on exactly what that collapse destroys.
 */
export type ChargeBlocker = 'authentication_required' | 'declined' | 'processing';

/**
 * The framing a payment notification carries to the invoice surface it opens.
 * Since 1.9.0, `deepLinkToPath`'s `invoice` arm emits this as `&reason=` so the
 * settle sheet can open under the same story the push told — a tap on "we tried
 * your card and it didn't go through" must not land on a neutral ledger.
 *
 * Deliberately NOT the client's own three-arm type: mobile carries a third
 * `'ledger'` arm as its local default for "no notification involved", which is
 * a client concern and does not belong on the wire.
 */
export type InvoiceDeepLinkReason = 'payment-failed' | 'payment-due';

export const INVOICE_DEEP_LINK_REASONS: readonly [
  InvoiceDeepLinkReason,
  ...InvoiceDeepLinkReason[],
] = ['payment-failed', 'payment-due'];

export type ReportProgram =
  | 'foundation'
  | 'advanced'
  | 'loose-leash'
  | 'house-manners'
  | 'cgc'
  | 'private-lesson'
  | 'boarding-session'
  | 'group-class-session'
  | 'board-train-session';

export type LocationKey = 'fayetteville' | 'bentonville';

export type RateUnit = 'per-day' | 'per-night' | 'per-session' | 'per-week' | 'flat';

export type StaffRole = 'owner-shanthi' | 'trainer' | 'office';

/** Attendance values a staff check-in can set. The DB `booking_attendance` enum
 *  also carries `'pending'` (the never-an-action default); the wire excludes it.
 *  `conformance.ts` asserts this is exactly `Exclude<booking_attendance, 'pending'>`. */
export type AttendanceStatus = 'attended' | 'no-show' | 'excused';

export type MediaPurpose =
  | 'dog-profile'
  | 'owner-avatar'
  | 'report-photo'
  | 'report-video'
  | 'message-attachment';

export type MediaKind = 'image' | 'video';

/** The 17 notification kinds an owner can receive. A hand-maintained mirror of
 *  the `notification_type` pgEnum; `conformance.ts` pins it to the Drizzle enum. */
export type NotificationType =
  | 'booking-confirmed'
  | 'report-published'
  | 'booking-cancelled'
  | 'announcement'
  | 'message-received'
  | 'booking-reminder'
  | 'boarding-profile-check'
  | 'credits-expiring'
  | 'payment-failed'
  | 'payment-succeeded'
  | 'alumni-attendance'
  | 'membership-ended'
  | 'spay-neuter-reminder'
  // R3 (Allison sim-QA 2026-07-27): the cash/check invoice reminder. Fires 24h
  // before the linked booking's drop-off (or 24h before the invoice due time when
  // unlinked), clamped to never land in the past — Allison 2026-07-31 raised the
  // lead from the original ~1h so the reminder arrives the day before, not the
  // morning of.
  | 'payment-due'
  // Allison 2026-07-29. The three below close the gaps she named in the
  // notification sweep:
  //   `invoice-overdue`  — the safety net: an invoice still open 3 days past due.
  //                        Every other payment path should have settled it long
  //                        before this fires, which is the point — it's a
  //                        precaution, not a dunning ladder. Fires ONCE.
  //   `card-expiring`    — the card on file is about to lapse (or just has), so
  //                        auto-charges don't start failing silently.
  //   `waitlist-spot-open`— a seat opened for a waitlisted entry (one freed up,
  //                        or staff overrode the cap). Named for what FIRES, not
  //                        for the outcome: it is an OFFER the owner must accept
  //                        or decline, and payment happens on accept — nothing is
  //                        booked or charged at this point (Allison 2026-07-29).
  | 'invoice-overdue'
  | 'card-expiring'
  | 'waitlist-spot-open';

/** The deep-link target a notification points at (`NotificationDeepLink.kind`).
 *  `deepLinkToPath` maps each arm to its owner-app route. `credits` is an alias
 *  of `dog-profile` (a credits alert routes to the affected dog); `credits` and
 *  `announcement` are reserved arms with no producer today. */
export type NotificationDeepLinkKind =
  | 'booking'
  | 'report'
  | 'thread'
  | 'invoice'
  | 'membership'
  | 'dog-profile'
  | 'dog-manage'
  | 'credits'
  | 'announcement'
  | 'payment-method'
  | 'waitlist';

// ---- enum value tuples (for `<select>` options + Zod `enum`) ---------------

export const SERVICE_CATEGORIES: readonly [ServiceCategory, ...ServiceCategory[]] = [
  'day-school',
  'day-care',
  'group-class',
  'private-lesson',
  'board-and-train',
  'boarding',
  'evaluation',
];

export const LOCATIONS: readonly [LocationKey, ...LocationKey[]] = ['fayetteville', 'bentonville'];

export const RATE_UNITS: readonly [RateUnit, ...RateUnit[]] = [
  'per-day',
  'per-night',
  'per-session',
  'per-week',
  'flat',
];

export const REPORT_PROGRAMS: readonly [ReportProgram, ...ReportProgram[]] = [
  'foundation',
  'advanced',
  'loose-leash',
  'house-manners',
  'cgc',
  'private-lesson',
  'boarding-session',
  'group-class-session',
  'board-train-session',
];

/** Report programs that carry a `*_content` variant doc (REQUIRED). The rest are
 *  curriculum programs that carry a `results` envelope and forbid `content`.
 *  `satisfies` guards against a typo slipping a non-program into the subset. */
export const SESSION_PROGRAMS = [
  'private-lesson',
  'boarding-session',
  'board-train-session',
  'group-class-session',
] as const satisfies readonly ReportProgram[];

export function isSessionProgram(program: ReportProgram): boolean {
  // `as` only widens the narrow `as const` tuple to the general union so
  // `.includes` accepts any ReportProgram — a provably-safe widening, never a
  // narrowing, so no runtime risk.
  return (SESSION_PROGRAMS as readonly ReportProgram[]).includes(program);
}

export const NOTIFICATION_DEEP_LINK_KINDS: readonly [
  NotificationDeepLinkKind,
  ...NotificationDeepLinkKind[],
] = [
  'booking',
  'report',
  'thread',
  'invoice',
  'membership',
  'dog-profile',
  'dog-manage',
  'credits',
  'announcement',
  'payment-method',
  'waitlist',
];

// ---- bookingWire.ts --------------------------------------------------------

export interface BookingWire {
  id: string;
  dog_id: string;
  additional_dog_ids?: string[];
  category: ServiceCategory;
  status: BookingStatus;
  date: string;
  trainer?: string;
  duration_minutes?: number;
  notes?: string;
  session_report_id?: string;
  location?: LocationKey;
  // The instant the free-cancel window closes (Δ 2026-07-08). Stamped at
  // creation from the active `cancel_window_settings` policy; omitted when null
  // (legacy-import rows pre-Day-10). The client reads it to warn, BEFORE a
  // cancel confirms, that cancelling now forfeits the credit/charge — powering
  // the booking-overlap "cancel it to book this" flow.
  cancel_deadline_at?: string;
  cancelled_at?: string;
  cancel_forfeited?: boolean;
  // Who cancelled + why (R5, Allison sim-QA 2026-07-27). Emitted only on a
  // cancelled booking, omit-on-null like `cancelled_at`. `cancelled_by` = 'owner'
  // (self-cancel → "You cancelled this on …") or 'staff' ("The school cancelled
  // this on …"); `cancel_reason` is the optional staff-supplied reason line.
  cancelled_by?: 'owner' | 'staff';
  cancel_reason?: string;
  // Group-class only (DATA-CONTRACT §A Amendment 2026-06-01). `cohort_id` is the
  // stable key the FE groups weekly sessions by; `group_class_name` titles the card.
  cohort_id?: string;
  group_class_name?: string;
  // Private-lesson only (Δ 2026-07-14): where the lesson happens — 'home'
  // (client's home) or 'public' (public spot). Owner-picked at request time,
  // copied onto the booking at approve; omitted on every other category.
  lesson_setting?: LessonSetting;
}

/** Δ 2026-07-14 — where a private lesson happens. */
export type LessonSetting = 'home' | 'public';

/** POST /staff/bookings/:id/attendance response (§A clarification 2026-05-28). */
export interface AttendanceWire {
  booking_id: string;
  dog_id: string;
  attendance: AttendanceStatus;
  checked_in_at: string;
}

// ---- requestWire.ts --------------------------------------------------------

export interface PendingRequestNotesWire {
  per_dog?: string;
  joint?: string;
}

export interface PendingRequestFocusWire {
  staff_preference?: string;
  // Δ 2026-06-17: staff-defined multi-select trait pills replaced the single
  // `comfort_level` enum.
  descriptor_keys?: string[];
}

export interface PendingRequestWire {
  id: string;
  dog_id: string;
  additional_dog_ids?: string[];
  category: ServiceCategory;
  submitted_at: string;
  preferred_dates: string[];
  notes?: PendingRequestNotesWire;
  focus: PendingRequestFocusWire;
  length_weeks?: number;
  status: RequestStatus;
  approved_at?: string;
  converted_booking_id?: string;
  // Day-program divert (Shanthi 2026-07-14): present only on diverted
  // day-school / day-care submissions. `divert_reasons` tells the staff
  // queue WHY this needs eyes ('reevaluation-stale' | 'not-spayed-neutered');
  // `location` + `payment` ride so the approve conversion books verbatim.
  location?: LocationKey;
  payment?: 'credits' | 'payg';
  divert_reasons?: string[];
  // Private-lesson only (Δ 2026-07-14): where the lesson should happen.
  lesson_setting?: LessonSetting;
}

/**
 * `POST /bookings` 202 response (Shanthi 2026-07-14): the submission tripped
 * an approval rule (3-month re-eval staleness / intact dog) and was parked as
 * a pending request instead of booking instantly. The 201 arm remains
 * `BookingWire[]` — clients branch on the status code.
 */
export interface DivertedBookingWire {
  diverted: true;
  divert_reasons: string[];
  request: PendingRequestWire;
}

/**
 * `POST /bookings/preview` response (Δ 2026-07-17): a read-only pre-check of
 * the approval-divert rules for a roster, so the owner app can ask up front —
 * "some dogs need staff approval; book the rest, request them too, or cancel?"
 * — BEFORE anything commits. Advisory only: POST /bookings re-runs the
 * authoritative check. One entry per requested dog; empty `divert_reasons`
 * means the dog books instantly.
 */
export interface BookingDivertPreviewDogWire {
  dog_id: string;
  divert_reasons: string[];
}

export interface BookingDivertPreviewWire {
  dogs: BookingDivertPreviewDogWire[];
}

// ---- threadWire.ts ---------------------------------------------------------

export interface ThreadParticipantWire {
  id: string;
  name: string;
  role: StaffRole;
  image_path?: string;
}

export interface ThreadWire {
  id: string;
  category: ThreadCategory;
  title: string;
  sub_text: string;
  participant: ThreadParticipantWire;
  related_dog_ids: string[];
  last_message: string;
  last_message_at: string;
  unread_count: number;
}

/** One photo/video attachment on a message. `url` is a short-lived signed GET
 *  (5-min TTL); width/height/blurhash let the FE lay out without a round-trip;
 *  `duration_ms` is video-only. */
export interface MessageAttachmentWire {
  media_id: string;
  kind: MediaKind;
  url: string;
  width: number | null;
  height: number | null;
  blurhash: string | null;
  duration_ms: number | null;
}

export interface MessageWire {
  id: string;
  thread_id: string;
  sender_id: string;
  sender_name?: string;
  text: string;
  /** Photo/video attachments, ordered as sent. Omitted when the message has none. */
  attachments?: MessageAttachmentWire[];
  sent_at: string;
  is_read: boolean;
}

// ---- reportWire.ts ---------------------------------------------------------

export interface SkillResult {
  status: 'pass' | 'learning' | 'pending';
  score?: string;
  meta?: { label: string; value: string }[];
}

export interface PracticeItem {
  text: string;
}

export interface ReportWire {
  id: string;
  dog_id: string;
  date: string;
  trainer?: string;
  category: ServiceCategory;
  program: ReportProgram;
  excerpt: string;
  full_text: string;
  visit_count?: number;
  verdict_headline?: string;
  results?: Record<string, SkillResult>;
  practice_at_home?: PracticeItem[];
  friends_today?: string[];
  additional_skills_completed?: string[];
  private_lesson_content?: unknown;
  boarding_session_content?: unknown;
  board_train_session_content?: unknown;
  group_class_session_content?: unknown;
}

// ---- notificationWire.ts ---------------------------------------------------

/**
 * A row in the owner notifications inbox (`GET /notifications`). snake_case keys
 * are the literal JSON on the wire. `is_read` is DERIVED from the DB's
 * `read_at IS NOT NULL` — the wire carries the boolean, not the timestamp. The
 * optional `?` keys (`deep_link_path`, `dog_ids`, `sender_staff_id`) are OMITTED
 * when null/empty, never emitted as null.
 */
export interface NotificationWire {
  id: string;
  type: NotificationType;
  title: string;
  body: string;
  received_at: string;
  is_read: boolean;
  deep_link_path?: string;
  dog_ids?: string[];
  sender_staff_id?: string;
}

/** `GET /notifications` response. `next_cursor` (a base64url keyset envelope) is
 *  omitted on the last page. */
export interface NotificationListResponse {
  items: NotificationWire[];
  next_cursor?: string;
}

/** `GET /notifications/unread-count` response. */
export interface UnreadCountResponse {
  unread_count: number;
}

/**
 * The `data` payload on an Expo push for a notification. snake_case is pinned
 * HERE so the push key can never drift from the wire the FE reads on tap.
 * `deep_link_path` is omitted when the notification has no target.
 */
export interface NotificationPushData {
  type: NotificationType;
  deep_link_path?: string;
  notification_id: string;
}

/**
 * A structured deep-link reference a producer stamps on a notification instead
 * of hand-writing a path. `deepLinkToPath` is the single grammar that turns it
 * into the owner-app route; `params` carries kind-specific extras (e.g. `report`
 * needs `dogId`).
 */
export interface NotificationDeepLink {
  kind: NotificationDeepLinkKind;
  id: string;
  params?: Record<string, string>;
}

/**
 * THE deep-link path grammar. Producers call this at emit time so the persisted
 * `deep_link_path` and the FE route table can never disagree. `report` requires
 * `params.dogId`; a missing one throws HERE — failing loud at emit time rather
 * than persisting a broken path. The inline `never` guard makes adding a kind to
 * `NotificationDeepLinkKind` without a case a compile error (this file is
 * dependency-free, so it can't import the shared `assertNever`).
 */
export function deepLinkToPath(link: NotificationDeepLink): string {
  switch (link.kind) {
    case 'booking':
      return `/bookings/${link.id}`;
    case 'report': {
      const dogId = link.params?.dogId;
      if (dogId === undefined || dogId === '') {
        throw new Error('deepLinkToPath: report link requires params.dogId');
      }
      return `/report-card/${dogId}?reportId=${link.id}`;
    }
    case 'thread':
      return `/chat/${link.id}`;
    case 'invoice': {
      // The SPECIFIC invoice (Allison 2026-07-27, decision 1): the owner app
      // opens it as a pop-up modal, so a paid invoice reads confirmed/paid — never
      // "Outstanding". `link.id` is the invoice id (producers pass it since Phase
      // 2), so it's load-bearing now, not a fixed route. Historical rows persist
      // the old query-less `/account/invoices`; the clients' parser keeps
      // accepting those (backward-compat rule) — only NEW emissions carry the id.
      //
      // Since 1.9.0 a payment notification also carries the FRAMING it promised
      // (`params.reason`), because the sheet it opens had no way to know which
      // push sent the owner there — Allison's 2026-07-31 payment-failed and
      // payment-due copy existed but no production host ever passed a reason, so
      // it rendered only under test. Invalid values throw at emit rather than
      // silently shipping a link the client will drop, matching the `report`
      // arm's fail-loud rule above. Omitted → byte-identical to the pre-1.9.0
      // path, so every historical row and every non-payment producer is untouched.
      const reason = link.params?.reason;
      if (reason === undefined) {
        return `/account/invoices?invoiceId=${link.id}`;
      }
      // Widen the tuple rather than narrowing `reason` — asserting it is a valid
      // member is exactly what this line exists to find out.
      if (!(INVOICE_DEEP_LINK_REASONS as readonly string[]).includes(reason)) {
        throw new Error(
          `deepLinkToPath: invoice link reason must be one of ${INVOICE_DEEP_LINK_REASONS.join(' | ')}, got ${reason}`,
        );
      }
      return `/account/invoices?invoiceId=${link.id}&reason=${reason}`;
    }
    case 'membership': {
      // Routing decided AT SEND TIME (Allison 2026-07-27, decision 4): a LONE
      // membership ending deep-links to that dog's subscriptions page; when the
      // SAME owner has MULTIPLE memberships completing in one worker tick
      // (simultaneous endings), the producer omits `params.dogId` so the tap lands
      // on the `/account/memberships` overview instead. `params.dogId` present ⇒
      // the dog page, carrying `?highlight=<membershipId>` so the app one-shot
      // flashes the SPECIFIC ended subscription card (Allison 2026-07-28, R4);
      // `link.id` is that membership id (producers pass it). Absent ⇒ the overview.
      // Historical rows persist the old query-less `/account/memberships` AND the
      // highlight-less `/dog-subscriptions/:dogId`; the parser keeps accepting both
      // (backward-compat rule).
      const dogId = link.params?.dogId;
      return dogId === undefined || dogId === ''
        ? '/account/memberships'
        : `/dog-subscriptions/${dogId}?highlight=${link.id}`;
    }
    case 'dog-profile':
      return `/dog-profile/${link.id}`;
    case 'dog-manage':
      return `/dog-manage/${link.id}`;
    // `credits` aliases `dog-profile` (decision 4): a credits alert routes to the
    // dog whose credits are expiring. `?highlight=credits` is a SENTINEL, not an
    // id — the credits card is a singular surface on that page, not one row among
    // many — and it makes the card one-shot flash so the alert lands on the thing
    // it's about rather than on the page it lives on (Allison 2026-07-29).
    case 'credits':
      return `/dog-profile/${link.id}?highlight=credits`;
    case 'announcement':
      return `/announcement/${link.id}`;
    // The expiring card, flashed in the wallet list (`link.id` is the
    // payment_method id) — same "point at the row, not the page" rule as invoice
    // and membership (Allison 2026-07-29).
    case 'payment-method':
      return `/payment-methods?highlight=${link.id}`;
    // A waitlist OFFER (`link.id` is the waitlist_entries id). Deliberately not
    // a booking link: when `waitlist-spot-open` fires nothing is booked yet —
    // the owner still has to accept, and payment happens on accept (Allison
    // 2026-07-30). Pointing at a booking that doesn't exist would 404.
    case 'waitlist':
      return `/waitlist/${link.id}`;
    default: {
      const unreachable: never = link.kind;
      throw new Error(`deepLinkToPath: unhandled kind ${String(unreachable)}`);
    }
  }
}

// ---- media (POST /media/upload + GET /media/:id) ---------------------------

/** `POST /media/upload` + `GET /media/:id` response. `url` + derivative URLs are
 *  short-lived presigned GETs; `derivatives` is empty until the derivatives
 *  worker runs (the source is still readable at original size — that's `url`). */
export interface MediaWire {
  id: string;
  purpose: MediaPurpose;
  kind: MediaKind;
  url: string;
  expires_at: string;
  blurhash: string | null;
  width: number | null;
  height: number | null;
  duration_ms: number | null;
  derivatives: Record<string, string>;
}

// ---- invoices (POST /invoices/:id/pay) -------------------------------------

/**
 * `POST /invoices/:id/pay` request body. Bodyless is still valid — every field
 * is optional and omitting the whole body is the pre-1.7.0 behaviour.
 *
 * `payment_method_id` is the card the owner picked at settle time. Before 1.7.0
 * the endpoint took no body at all and always charged the invoice's BOUND card,
 * so the mobile pay sheet's card picker was decorative: an owner could select
 * "Mastercard ••8203" and be charged their Visa. Naming the card here is what
 * makes that picker true.
 *
 * Optional rather than required, deliberately:
 *   - a client that omits it keeps the old behaviour (charge the bound card),
 *     so this is a minor bump and no client has to move in lockstep;
 *   - the idempotency request hash is canonical JSON, which DROPS
 *     `undefined`-valued keys, so an omitted card hashes byte-identically to the
 *     pre-1.7.0 `{ id }` body and no in-flight Idempotency-Key breaks;
 *   - two calls naming DIFFERENT cards now hash differently, which closes a real
 *     hazard: under the old `hashRequestBody({ id })` they collided, so the
 *     second call replayed the first's stored response and the owner was told a
 *     card had been charged that never was.
 *
 * The server verifies the card is a LIVE card of the calling owner and 404s
 * otherwise (tenancy misses collapse to 404 rather than 403 to avoid probing),
 * then repoints `invoices.payment_method_id` at it inside the settle
 * transaction so the receipt names the card actually charged.
 */
export interface InvoicePayRequest {
  payment_method_id?: string;
}

/**
 * `POST /invoices/:id/pay` response. Declared here since 1.7.0; it previously
 * lived in `routes/invoices.ts`, which left the money endpoint entirely outside
 * the versioned contract with nothing for the clients' `check:contracts` to
 * guard. Shape unchanged by the move.
 */
export interface InvoicePayWire {
  charge_id: string;
  charge_status: ChargeStatus;
  stripe_payment_intent_id: string;
  /**
   * Stripe's client secret for the PaymentIntent. **Do not treat this as a
   * completable intent.** Since 1.7.1 every path that confirms an off-session
   * PaymentIntent and observes a non-succeeded status best-effort CANCELS it
   * before returning, because no client-side 3DS completion flow exists
   * anywhere in this system and an uncancelled intent can later auto-succeed
   * and double-charge against the next attempt's fresh intent. So on the
   * non-succeeded arm this names a cancelled intent and there is nothing a
   * client can do with it; it is returned for logging and support lookup only.
   * A client that "completes" it is building on a dead reference.
   *
   * When a 3DS-completion design lands it must revisit the cancel rule for
   * on-session routes -- completion needs a LIVE intent -- and re-document this
   * field in the same change.
   */
  client_secret: string | null;
  invoice_status: 'open' | 'paid' | 'void';
  /**
   * True when this charge succeeded at Stripe but LOST the settle race against
   * a concurrent worker auto-charge (or webhook) -- the invoice is already
   * `paid` by that path, so this duplicate charge is being refunded post-commit
   * (a 'pending' refund row was written in-tx; Stripe + webhook reconcile it).
   * The owner's card nets exactly one charge. Honest signal so the client
   * never renders "payment complete" for money that's on its way back. False
   * on the clean win and on the 3DS / requires_action path.
   */
  charge_refunded: boolean;
  /**
   * Why this confirm stopped short of `succeeded`, at the domain level.
   * Present IFF the response reports a non-succeeded confirm; omitted on every
   * settled arm, and absent on stored idempotency replays of pre-1.8.0
   * responses -- derive pessimistically when missing.
   *
   * The 1.8.0 gloss pinned presence to `charge_status: 'requires_payment'`,
   * which was false: a `canceled` raw status maps to `charge_status: 'failed'`
   * (`stripe.ts` status collapse) and still carries a blocker. Corrected in
   * 1.9.0 -- branch on the blocker's presence, never on a status pairing.
   *
   * Since 1.9.0 this is the taxonomy for BOTH Stripe behaviors, not one of
   * them. A card error THROWN by an off-session confirm is normalized at the
   * Stripe seam into the same non-succeeded result the returning fork
   * produces, so whichever way Stripe reports a decline, the owner reads the
   * same specific sentence. That is what makes `[1.8.0]`'s "one taxonomy
   * across both channels" true rather than aspirational.
   *
   * This is NOT an invitation to complete authentication: per the 1.7.1 cancel
   * rule the intent behind `client_secret` is already cancelled on this arm.
   * The field exists for (a) honest, specific copy today and (b) the future
   * 3DS-completion design, which needs this signal on a LIVE intent and
   * revisits the cancel rule -- the field survives that change unmodified;
   * only the cancel clause of `client_secret`'s comment does.
   */
  charge_blocker?: ChargeBlocker;
}

/**
 * `POST /credit-packages/:key/purchase` response. Declared here since 1.8.0;
 * it previously lived in `routes/creditPackages.ts`, which left a second money
 * endpoint outside the versioned contract with nothing for the clients'
 * `check:contracts` to guard -- the same condition that let the invoice card
 * picker drift in the first place. Shape unchanged by the move; `charge_blocker`
 * is the only addition.
 */
export interface CreditPurchaseWire {
  charge_id: string;
  charge_status: ChargeStatus;
  stripe_payment_intent_id: string;
  /** Same caveat as `InvoicePayWire.client_secret`: on the non-succeeded arm
   *  this names a CANCELLED intent (1.7.1 cancel rule) and cannot be completed. */
  client_secret: string | null;
  /** Zero on every non-succeeded arm -- the grant is gated on `succeeded`. */
  credits_granted: number;
  /** See `InvoicePayWire.charge_blocker`. Same union, same derivation, same
   *  pessimistic-when-absent rule. */
  charge_blocker?: ChargeBlocker;
}

// ---- GET /staff/dogs -------------------------------------------------------

/** Dog directory for the cross-owner staff verbs (which reference dogs by UUID
 *  and carry no names). Resolves dog_id → name + owner for display. */
export interface StaffDogWire {
  id: string;
  name: string;
  breed: string;
  owner_id: string;
  owner_name: string;
  profile_image_path?: string;
}

// ---- staff/rates (append-only / void / history) ---------------------------

/** Staff-config view of the effective-dated price catalog. Rows are addressable
 *  (`id`) for void/edit; `effective_to`/`created_by_staff_id`/`note`/`location`
 *  always present (vs the owner-facing read). */
export interface StaffRateWire {
  id: string;
  category: ServiceCategory;
  location: LocationKey | null;
  amount_cents: number;
  unit: RateUnit;
  effective_from: string;
  effective_to: string | null;
  note: string | null;
  created_by_staff_id: string | null;
}

export interface StaffRateHistoryWire extends StaffRateWire {
  created_at: string;
  voided_at: string | null;
  voided_by_staff_id: string | null;
}
