/**
 * THE shared API↔client wire contract — single source of truth.
 *
 * This module is **dependency-free on purpose**: no imports (not Drizzle, not
 * anything). It is the file the staff portal's `src/api/contracts.ts` is
 * GENERATED from (verbatim + a banner, via the portal's `npm run sync:contracts`),
 * so it must never drag server code (Drizzle schema, Node APIs) into a browser
 * bundle. Keep it pure types + literal value tuples + pure helpers.
 *
 * Two halves:
 *   1. **Enum unions + value tuples.** Declared here as literals. Their values
 *      are canonically owned by the DB (`schema.sql` → Drizzle `pgEnum`); the
 *      literals here are a hand-maintained mirror that `contracts/conformance.ts`
 *      pins to the Drizzle enums with a compile-time `Equal<…>` assert — so if
 *      `schema.sql` changes an enum, `tsc` fails until this file is updated.
 *      (We assert rather than rewire `pgEnum(...)` because `schema.ts` is
 *      drizzle-introspection-generated and a `db:introspect` pull would clobber
 *      any hand-wired tuple import.)
 *   2. **Wire interfaces.** The JSON shapes the API emits. snake_case keys are
 *      intentional — they're the literal JSON keys on the wire. These have no
 *      other canonical home, so THIS file is their single definition; the API's
 *      `lib/*Wire.ts` + the staff routes import them from here.
 */

// ---- contract version ------------------------------------------------------

/**
 * Semver for this contract. Bump on EVERY edit to this file, log the change in
 * `src/contracts/CHANGELOG.md`, and resync BOTH generated clients (portal +
 * mobile `npm run sync:contracts`) in their own repos' commits:
 *   major — remove/rename/retype an existing field or enum member
 *   minor — additive (new field, interface, enum member, tuple value)
 *   patch — comment/doc-only (still changes generated bytes → still resync)
 */
export const WIRE_CONTRACT_VERSION = '1.3.0';

// ---- enum unions -----------------------------------------------------------

export type ServiceCategory =
  | 'day-school'
  | 'day-care'
  | 'group-class'
  | 'private-lesson'
  | 'board-and-train'
  | 'boarding'
  | 'evaluation';

export type BookingStatus = 'upcoming' | 'past' | 'cancelled';

export type RequestStatus =
  | 'submitted'
  | 'approved'
  | 'approved-awaiting-payment'
  | 'converted'
  | 'cancelled';

export type ThreadCategory = 'sessions' | 'billing' | 'enrollment' | 'other';

export type ReportProgram =
  | 'foundation'
  | 'advanced'
  | 'loose-leash'
  | 'house-manners'
  | 'cgc'
  | 'private-lesson'
  | 'boarding-session'
  | 'group-class-session'
  | 'board-train-session';

export type LocationKey = 'fayetteville' | 'bentonville';

export type RateUnit = 'per-day' | 'per-night' | 'per-session' | 'per-week' | 'flat';

export type StaffRole = 'owner-shanthi' | 'trainer' | 'office';

/** Attendance values a staff check-in can set. The DB `booking_attendance` enum
 *  also carries `'pending'` (the never-an-action default); the wire excludes it.
 *  `conformance.ts` asserts this is exactly `Exclude<booking_attendance, 'pending'>`. */
export type AttendanceStatus = 'attended' | 'no-show' | 'excused';

export type MediaPurpose =
  | 'dog-profile'
  | 'owner-avatar'
  | 'report-photo'
  | 'report-video'
  | 'message-attachment';

export type MediaKind = 'image' | 'video';

/** The 14 notification kinds an owner can receive. A hand-maintained mirror of
 *  the `notification_type` pgEnum; `conformance.ts` pins it to the Drizzle enum. */
export type NotificationType =
  | 'booking-confirmed'
  | 'report-published'
  | 'booking-cancelled'
  | 'announcement'
  | 'message-received'
  | 'booking-reminder'
  | 'boarding-profile-check'
  | 'credits-expiring'
  | 'payment-failed'
  | 'payment-succeeded'
  | 'alumni-attendance'
  | 'membership-ended'
  | 'spay-neuter-reminder'
  // R3 (Allison sim-QA 2026-07-27): the cash/check invoice reminder — fires ~1h
  // before the linked booking's drop-off (or the invoice due time when unlinked).
  | 'payment-due';

/** The deep-link target a notification points at (`NotificationDeepLink.kind`).
 *  `deepLinkToPath` maps each arm to its owner-app route. `credits` is an alias
 *  of `dog-profile` (a credits alert routes to the affected dog); `credits` and
 *  `announcement` are reserved arms with no producer today. */
export type NotificationDeepLinkKind =
  | 'booking'
  | 'report'
  | 'thread'
  | 'invoice'
  | 'membership'
  | 'dog-profile'
  | 'dog-manage'
  | 'credits'
  | 'announcement';

// ---- enum value tuples (for `<select>` options + Zod `enum`) ---------------

export const SERVICE_CATEGORIES: readonly [ServiceCategory, ...ServiceCategory[]] = [
  'day-school',
  'day-care',
  'group-class',
  'private-lesson',
  'board-and-train',
  'boarding',
  'evaluation',
];

export const LOCATIONS: readonly [LocationKey, ...LocationKey[]] = ['fayetteville', 'bentonville'];

export const RATE_UNITS: readonly [RateUnit, ...RateUnit[]] = [
  'per-day',
  'per-night',
  'per-session',
  'per-week',
  'flat',
];

export const REPORT_PROGRAMS: readonly [ReportProgram, ...ReportProgram[]] = [
  'foundation',
  'advanced',
  'loose-leash',
  'house-manners',
  'cgc',
  'private-lesson',
  'boarding-session',
  'group-class-session',
  'board-train-session',
];

/** Report programs that carry a `*_content` variant doc (REQUIRED). The rest are
 *  curriculum programs that carry a `results` envelope and forbid `content`.
 *  `satisfies` guards against a typo slipping a non-program into the subset. */
export const SESSION_PROGRAMS = [
  'private-lesson',
  'boarding-session',
  'board-train-session',
  'group-class-session',
] as const satisfies readonly ReportProgram[];

export function isSessionProgram(program: ReportProgram): boolean {
  // `as` only widens the narrow `as const` tuple to the general union so
  // `.includes` accepts any ReportProgram — a provably-safe widening, never a
  // narrowing, so no runtime risk.
  return (SESSION_PROGRAMS as readonly ReportProgram[]).includes(program);
}

export const NOTIFICATION_DEEP_LINK_KINDS: readonly [
  NotificationDeepLinkKind,
  ...NotificationDeepLinkKind[],
] = [
  'booking',
  'report',
  'thread',
  'invoice',
  'membership',
  'dog-profile',
  'dog-manage',
  'credits',
  'announcement',
];

// ---- bookingWire.ts --------------------------------------------------------

export interface BookingWire {
  id: string;
  dog_id: string;
  additional_dog_ids?: string[];
  category: ServiceCategory;
  status: BookingStatus;
  date: string;
  trainer?: string;
  duration_minutes?: number;
  notes?: string;
  session_report_id?: string;
  location?: LocationKey;
  // The instant the free-cancel window closes (Δ 2026-07-08). Stamped at
  // creation from the active `cancel_window_settings` policy; omitted when null
  // (legacy-import rows pre-Day-10). The client reads it to warn, BEFORE a
  // cancel confirms, that cancelling now forfeits the credit/charge — powering
  // the booking-overlap "cancel it to book this" flow.
  cancel_deadline_at?: string;
  cancelled_at?: string;
  cancel_forfeited?: boolean;
  // Who cancelled + why (R5, Allison sim-QA 2026-07-27). Emitted only on a
  // cancelled booking, omit-on-null like `cancelled_at`. `cancelled_by` = 'owner'
  // (self-cancel → "You cancelled this on …") or 'staff' ("The school cancelled
  // this on …"); `cancel_reason` is the optional staff-supplied reason line.
  cancelled_by?: 'owner' | 'staff';
  cancel_reason?: string;
  // Group-class only (DATA-CONTRACT §A Amendment 2026-06-01). `cohort_id` is the
  // stable key the FE groups weekly sessions by; `group_class_name` titles the card.
  cohort_id?: string;
  group_class_name?: string;
  // Private-lesson only (Δ 2026-07-14): where the lesson happens — 'home'
  // (client's home) or 'public' (public spot). Owner-picked at request time,
  // copied onto the booking at approve; omitted on every other category.
  lesson_setting?: LessonSetting;
}

/** Δ 2026-07-14 — where a private lesson happens. */
export type LessonSetting = 'home' | 'public';

/** POST /staff/bookings/:id/attendance response (§A clarification 2026-05-28). */
export interface AttendanceWire {
  booking_id: string;
  dog_id: string;
  attendance: AttendanceStatus;
  checked_in_at: string;
}

// ---- requestWire.ts --------------------------------------------------------

export interface PendingRequestNotesWire {
  per_dog?: string;
  joint?: string;
}

export interface PendingRequestFocusWire {
  staff_preference?: string;
  // Δ 2026-06-17: staff-defined multi-select trait pills replaced the single
  // `comfort_level` enum.
  descriptor_keys?: string[];
}

export interface PendingRequestWire {
  id: string;
  dog_id: string;
  additional_dog_ids?: string[];
  category: ServiceCategory;
  submitted_at: string;
  preferred_dates: string[];
  notes?: PendingRequestNotesWire;
  focus: PendingRequestFocusWire;
  length_weeks?: number;
  status: RequestStatus;
  approved_at?: string;
  converted_booking_id?: string;
  // Day-program divert (Shanthi 2026-07-14): present only on diverted
  // day-school / day-care submissions. `divert_reasons` tells the staff
  // queue WHY this needs eyes ('reevaluation-stale' | 'not-spayed-neutered');
  // `location` + `payment` ride so the approve conversion books verbatim.
  location?: LocationKey;
  payment?: 'credits' | 'payg';
  divert_reasons?: string[];
  // Private-lesson only (Δ 2026-07-14): where the lesson should happen.
  lesson_setting?: LessonSetting;
}

/**
 * `POST /bookings` 202 response (Shanthi 2026-07-14): the submission tripped
 * an approval rule (3-month re-eval staleness / intact dog) and was parked as
 * a pending request instead of booking instantly. The 201 arm remains
 * `BookingWire[]` — clients branch on the status code.
 */
export interface DivertedBookingWire {
  diverted: true;
  divert_reasons: string[];
  request: PendingRequestWire;
}

/**
 * `POST /bookings/preview` response (Δ 2026-07-17): a read-only pre-check of
 * the approval-divert rules for a roster, so the owner app can ask up front —
 * "some dogs need staff approval; book the rest, request them too, or cancel?"
 * — BEFORE anything commits. Advisory only: POST /bookings re-runs the
 * authoritative check. One entry per requested dog; empty `divert_reasons`
 * means the dog books instantly.
 */
export interface BookingDivertPreviewDogWire {
  dog_id: string;
  divert_reasons: string[];
}

export interface BookingDivertPreviewWire {
  dogs: BookingDivertPreviewDogWire[];
}

// ---- threadWire.ts ---------------------------------------------------------

export interface ThreadParticipantWire {
  id: string;
  name: string;
  role: StaffRole;
  image_path?: string;
}

export interface ThreadWire {
  id: string;
  category: ThreadCategory;
  title: string;
  sub_text: string;
  participant: ThreadParticipantWire;
  related_dog_ids: string[];
  last_message: string;
  last_message_at: string;
  unread_count: number;
}

/** One photo/video attachment on a message. `url` is a short-lived signed GET
 *  (5-min TTL); width/height/blurhash let the FE lay out without a round-trip;
 *  `duration_ms` is video-only. */
export interface MessageAttachmentWire {
  media_id: string;
  kind: MediaKind;
  url: string;
  width: number | null;
  height: number | null;
  blurhash: string | null;
  duration_ms: number | null;
}

export interface MessageWire {
  id: string;
  thread_id: string;
  sender_id: string;
  sender_name?: string;
  text: string;
  /** Photo/video attachments, ordered as sent. Omitted when the message has none. */
  attachments?: MessageAttachmentWire[];
  sent_at: string;
  is_read: boolean;
}

// ---- reportWire.ts ---------------------------------------------------------

export interface SkillResult {
  status: 'pass' | 'learning' | 'pending';
  score?: string;
  meta?: { label: string; value: string }[];
}

export interface PracticeItem {
  text: string;
}

export interface ReportWire {
  id: string;
  dog_id: string;
  date: string;
  trainer?: string;
  category: ServiceCategory;
  program: ReportProgram;
  excerpt: string;
  full_text: string;
  visit_count?: number;
  verdict_headline?: string;
  results?: Record<string, SkillResult>;
  practice_at_home?: PracticeItem[];
  friends_today?: string[];
  additional_skills_completed?: string[];
  private_lesson_content?: unknown;
  boarding_session_content?: unknown;
  board_train_session_content?: unknown;
  group_class_session_content?: unknown;
}

// ---- notificationWire.ts ---------------------------------------------------

/**
 * A row in the owner notifications inbox (`GET /notifications`). snake_case keys
 * are the literal JSON on the wire. `is_read` is DERIVED from the DB's
 * `read_at IS NOT NULL` — the wire carries the boolean, not the timestamp. The
 * optional `?` keys (`deep_link_path`, `dog_ids`, `sender_staff_id`) are OMITTED
 * when null/empty, never emitted as null.
 */
export interface NotificationWire {
  id: string;
  type: NotificationType;
  title: string;
  body: string;
  received_at: string;
  is_read: boolean;
  deep_link_path?: string;
  dog_ids?: string[];
  sender_staff_id?: string;
}

/** `GET /notifications` response. `next_cursor` (a base64url keyset envelope) is
 *  omitted on the last page. */
export interface NotificationListResponse {
  items: NotificationWire[];
  next_cursor?: string;
}

/** `GET /notifications/unread-count` response. */
export interface UnreadCountResponse {
  unread_count: number;
}

/**
 * The `data` payload on an Expo push for a notification. snake_case is pinned
 * HERE so the push key can never drift from the wire the FE reads on tap.
 * `deep_link_path` is omitted when the notification has no target.
 */
export interface NotificationPushData {
  type: NotificationType;
  deep_link_path?: string;
  notification_id: string;
}

/**
 * A structured deep-link reference a producer stamps on a notification instead
 * of hand-writing a path. `deepLinkToPath` is the single grammar that turns it
 * into the owner-app route; `params` carries kind-specific extras (e.g. `report`
 * needs `dogId`).
 */
export interface NotificationDeepLink {
  kind: NotificationDeepLinkKind;
  id: string;
  params?: Record<string, string>;
}

/**
 * THE deep-link path grammar. Producers call this at emit time so the persisted
 * `deep_link_path` and the FE route table can never disagree. `report` requires
 * `params.dogId`; a missing one throws HERE — failing loud at emit time rather
 * than persisting a broken path. The inline `never` guard makes adding a kind to
 * `NotificationDeepLinkKind` without a case a compile error (this file is
 * dependency-free, so it can't import the shared `assertNever`).
 */
export function deepLinkToPath(link: NotificationDeepLink): string {
  switch (link.kind) {
    case 'booking':
      return `/bookings/${link.id}`;
    case 'report': {
      const dogId = link.params?.dogId;
      if (dogId === undefined || dogId === '') {
        throw new Error('deepLinkToPath: report link requires params.dogId');
      }
      return `/report-card/${dogId}?reportId=${link.id}`;
    }
    case 'thread':
      return `/chat/${link.id}`;
    case 'invoice':
      // The SPECIFIC invoice (Allison 2026-07-27, decision 1): the owner app
      // opens it as a pop-up modal, so a paid invoice reads confirmed/paid — never
      // "Outstanding". `link.id` is the invoice id (producers pass it since Phase
      // 2), so it's load-bearing now, not a fixed route. Historical rows persist
      // the old query-less `/account/invoices`; the clients' parser keeps
      // accepting those (backward-compat rule) — only NEW emissions carry the id.
      return `/account/invoices?invoiceId=${link.id}`;
    case 'membership': {
      // Routing decided AT SEND TIME (Allison 2026-07-27, decision 4): a LONE
      // membership ending deep-links to that dog's subscriptions page; when the
      // SAME owner has MULTIPLE memberships completing in one worker tick
      // (simultaneous endings), the producer omits `params.dogId` so the tap lands
      // on the `/account/memberships` overview instead. `params.dogId` present ⇒
      // the dog page; absent ⇒ the overview. Historical rows persist the old
      // query-less `/account/memberships`; the parser keeps accepting those
      // (backward-compat rule).
      const dogId = link.params?.dogId;
      return dogId === undefined || dogId === ''
        ? '/account/memberships'
        : `/dog-subscriptions/${dogId}`;
    }
    case 'dog-profile':
      return `/dog-profile/${link.id}`;
    case 'dog-manage':
      return `/dog-manage/${link.id}`;
    // `credits` aliases `dog-profile` (decision 4): a credits alert routes to the
    // dog whose credits are expiring.
    case 'credits':
      return `/dog-profile/${link.id}`;
    case 'announcement':
      return `/announcement/${link.id}`;
    default: {
      const unreachable: never = link.kind;
      throw new Error(`deepLinkToPath: unhandled kind ${String(unreachable)}`);
    }
  }
}

// ---- media (POST /media/upload + GET /media/:id) ---------------------------

/** `POST /media/upload` + `GET /media/:id` response. `url` + derivative URLs are
 *  short-lived presigned GETs; `derivatives` is empty until the derivatives
 *  worker runs (the source is still readable at original size — that's `url`). */
export interface MediaWire {
  id: string;
  purpose: MediaPurpose;
  kind: MediaKind;
  url: string;
  expires_at: string;
  blurhash: string | null;
  width: number | null;
  height: number | null;
  duration_ms: number | null;
  derivatives: Record<string, string>;
}

// ---- GET /staff/dogs -------------------------------------------------------

/** Dog directory for the cross-owner staff verbs (which reference dogs by UUID
 *  and carry no names). Resolves dog_id → name + owner for display. */
export interface StaffDogWire {
  id: string;
  name: string;
  breed: string;
  owner_id: string;
  owner_name: string;
  profile_image_path?: string;
}

// ---- staff/rates (append-only / void / history) ---------------------------

/** Staff-config view of the effective-dated price catalog. Rows are addressable
 *  (`id`) for void/edit; `effective_to`/`created_by_staff_id`/`note`/`location`
 *  always present (vs the owner-facing read). */
export interface StaffRateWire {
  id: string;
  category: ServiceCategory;
  location: LocationKey | null;
  amount_cents: number;
  unit: RateUnit;
  effective_from: string;
  effective_to: string | null;
  note: string | null;
  created_by_staff_id: string | null;
}

export interface StaffRateHistoryWire extends StaffRateWire {
  created_at: string;
  voided_at: string | null;
  voided_by_staff_id: string | null;
}
